name: Compile and Test

on:
  workflow_call:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Code
        run: |
          echo "Compiling the codebase..."

      - name: Run Tests
        run: |
          echo "Running tests on changed files..."