name: Dependent Job

on:
  workflow_call:

jobs:
  dependent-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "🔗 This job runs after the 'main-job' completes."
      - run: echo "🚀 Performing dependent tasks now."
      - run: echo "✨ Dependent job finished successfully!"
