name: Android Checks
description: Run any Android specific checks for linting, testing, etc.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    # - uses: actions/setup-java@v4
    #   with:
    #     java-version: '21'
    #     distribution: 'temurin'

    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@v4

    - name: Print environment required value
      shell: bash
      run: |
        echo "My secret is $SOMETHING"
        echo "My other secret is $SOMETHING_ELSE"

    - name: Inject Gradle Properties
      working-directory: Android/
      shell: bash
      run: |
        echo "required_value=$SOMETHING" >> ./gradle.properties
        echo "another_value=$SOMETHING_ELSE" >> ./gradle.properties

    - name: Check Gradle Properties
      working-directory: Android/
      shell: bash
      run: |
        ./gradlew properties

    # - name: Run unit tests
    #   shell: bash
    #   working-directory: ./Android
    #   run: ./gradlew assembleUnitTest

    # - name: Build debug variant
    #   shell: bash
    #   working-directory: ./Android
    #   run: ./gradlew assembleDebug