name: Android Checks (Composite Action)
description: Run any Android specific checks for linting, testing, etc.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run unit tests
      shell: bash
      working-directory: ./Android
      run: echo "Test"

    - name: Build debug variant
      shell: bash
      working-directory: ./Android
      run: echo "Something else"
