name: Android Checks
description: Run any Android specific checks for linting, testing, etc.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Inject Gradle Properties
      working-directory: Android/
      shell: bash
      run: |
        echo "" >> ./gradle.properties
        echo "required_value=$SOMETHING" >> ./gradle.properties
        echo "another_value=$SOMETHING_ELSE" >> ./gradle.properties

    - name: Run unit tests
      shell: bash
      working-directory: ./Android
      run: ./gradlew assembleUnitTest

    - name: Build debug variant
      shell: bash
      working-directory: ./Android
      run: ./gradlew assembleDebug