name: Android Checks
description: Run any Android specific checks for linting, testing, etc.

runs:
  using: composite
  steps:
    - name: Build and test
      runs-on: ubuntu-latest
      shell: bash
      run: |
        echo "Starting Android checks..."