name: Android Checks
description: Run any Android specific checks for linting, testing, etc.

runs:
  using: composite
  steps:
    # - uses: actions/checkout@v4
    # - uses: actions/setup-java@v4
    #   with:
    #     java-version: '21'
    #     distribution: 'temurin'

    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@v4

    - name: Get secrets
      shell: bash
      run: |
        echo 'MY_REQUIRED_VALUE="my_required_value"' >> $GITHUB_ENV

    - name: Print environment required value
      shell: bash
      run: |
        echo "My secret is $MY_REQUIRED_VALUE"

    # - name: Run unit tests
    #   shell: bash
    #   working-directory: ./Android
    #   run: ./gradlew assembleUnitTest

    # - name: Build debug variant
    #   shell: bash
    #   working-directory: ./Android
    #   run: ./gradlew assembleDebug