name: Initialise Android
description: Set up anything relating to Android workflows

inputs:
  required_value:
    type: string
    description: Some required value for the Gradle project
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Set Gradle Project Variables
      shell: bash
      run: |
        echo "ORG_GRADLE_PROJECT_required_value=${{ inputs.required_value }}" >> $GITHUB_ENV
