name: Check Commit Messages
description: Validates that all commit messages adhere to a specific format.
author: Thomas Dib
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  pattern:
    description: "Regex pattern to validate commit messages"
    required: true
    default: '^(([A-Z]+-\\d+)|\\[CI\\]|\\[Release\\]|\\[QA\\]|\\[Merge\\]|\\[Automation\\]) .+'
  error-message:
    description: "Error message to display for invalid commits"
    required: true
    default: "Invalid commit message format."
