name: Android Checks

on:
  workflow_call:
    inputs:
      required_value:
        type: string
        description: Some required value for the Gradle project
        required: true
  workflow_dispatch:
  workflow_call:

jobs:
  android-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Gradle Project Variables
        run: |
          echo "ORG_GRADLE_PROJECT_required_value=${{ inputs.required_value }}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # - name: Run unit tests
      #   run: ./gradlew assembleUnitTest

      # - name: Build debug variant
      #   run: ./gradlew assembleDebug