name: PR Checks
run-name: "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches:
      - main

jobs:
  test-job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: PR test job
        run: |
          echo "This is a test job"

