name: Android Checks
run-name: Android Checks - PR #${{ github.event.pull_request.number }}

on:
  pull_request:
    branches:
      - main

jobs:
  android-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests
        run: ./gradlew assembleUnitTest
