name: PR Checks
run-name: "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  check-commit-messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Commit Messages
        uses: ./.github/actions/commit-message-validator
        with:
          # Match examples: "ABCD-1234 Commit msg", "[Release] Commit msg", "[QA] Commit msg"
          # pattern: '^(([A-Z]+\-\d+)|\[CI\]|\[Release\]|\[QA\]|\[Merge\]|\[Automation\]) .+$'
          pattern: "^.*$" # Temporarily allow anything
          error-message: "All commit messages must start with a Jira ticket or a valid prefix."
          github-token: ${{ secrets.GITHUB_TOKEN }}

  label-changes:
    name: Label Changes
    runs-on: ubuntu-latest
    steps:
      - name: Label Changes
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  detect-file-changes:
    runs-on: ubuntu-latest
    name: Detect file changes
    outputs:
      run_android: ${{ steps.detect.outputs.run_android }}
      run_ios: ${{ steps.detect.outputs.run_ios }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect File Changes
        id: detect
        # Check changed files for "Android/" or "iOS/" in the path and set the respective flags to indicate changes
        run: |
          if git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep -q 'Android/'; then
            echo "Android changes detected"
            echo "run_android=true" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep -q 'iOS/'; then
            echo "iOS changes detected"
            echo "run_ios=true" >> $GITHUB_OUTPUT
          fi

  android-checks:
    name: Android Checks
    needs: detect-file-changes
    if: ${{ needs.detect-file-changes.outputs.run_android == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Android Checks
        uses: ./.github/actions/android-checks

  ios-checks:
    name: iOS Checks
    needs: detect-file-changes
    if: ${{ needs.detect-file-changes.outputs.run_ios == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run iOS Checks
        uses: ./.github/actions/ios-checks