name: PR Checks
run-name: PR Checks!

on:
  pull_request:
    branches:
      - main

jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Validating merge
        run: |
          echo "Validating merge..."
          echo "--------------"
          git log

