name: PR Checks
run-name: PR Checks!

on:
  pull_request:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: "PR test job"
        run: |
          echo "Running scheduled main checks"
          echo "This is a cron job"
          echo "This job runs every 5 minutes"
          echo "This job is triggered by a cron schedule"
          echo "This job is triggered by a manual workflow_dispatch event"

