name: PR Checks
run-name: PR Checks!

on:
  pull_request:
    branches:
      - main

jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          echo "Fetching main branch..."
          git fetch main

      - name: Create Temporary Merge
        run: |
          echo "Checking out main"
          git checkout main
          echo "Merging origin/${{github.head_ref}}"
          git merge --no-commit --no-ff origin/${{ github.head_ref }}
      
      - name: Validating Merge
        run: |
          echo "Validating merge..."
          echo "--------------"
          echo ${{ github.head_ref }}
          echo "--------------"
          git log

