name: Scheduled Main Checks

on:
  # schedule:
  #   - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Main test job"
        run: |
          echo "Running scheduled main checks"
          echo "This is a cron job"
          echo "This job runs every 5 minutes"
          echo "This job is triggered by a cron schedule"
          echo "This job is triggered by a manual workflow_dispatch event"
