name: PR Checks
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main

jobs:
  main-job:
    uses: ./.github/workflows/job_main.yml

  secondary-job:
    uses: ./.github/workflows/job_secondary.yml

  dependent-job:
    needs: main-job
    uses: ./.github/workflows/job_dependent.yml
