name: Scheduled Main Checks

on:
  # schedule:
  #   - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch:

jobs:
  check-for-changes:
    uses: ./.github/workflows/job_check-for-changes.yml

  compile-and-test:
    needs: check-for-changes
    uses: ./.github/workflows/job_compile-and-test.yml