name: PR Checks
run-name: PR Checks!

on:
  pull_request:
    branches:
      - main

jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          echo "Fetching main branch..."
          git fetch origin main
          echo "Fetching PR branch..."
          git fetch origin ${{ github.head_ref }}

      - name: Checkout PR branch
        run: |
          git checkout ${{ github.head_ref }}

      - name: Create temporary merge
        run: |
          git checkout -b temp-merge
          git merge --no-commit --no-ff origin/main
      
      - name: Validating merge
        run: |
          echo "Validating merge..."
          echo "--------------"
          echo ${{ github.head_ref }}
          echo "--------------"
          git log

